### ISSUE TITLE
Item Problems on Windows

### ISSUE THREAD

**Issue by iKramp** [Zorz42/Terralistic#51]
Downloaded Terralistic from itch for windows and started playing. Item velocity seems to be calculated differently between clients and server on windows and it sometimes crashes when you pick up an item

https://user-images.githubusercontent.com/60236692/134575586-16ba7488-51f9-4145-8f5e-70097012eba2.mp4

https://user-images.githubusercontent.com/60236692/134575589-48c894b3-4044-4cc7-ac95-3cbad6b7e0da.mp4

.

**Comment by Zorz42** [comment]
fixed in alpha-0.3.0
