### ISSUE TITLE
Which ores should be added? 

### ISSUE THREAD

**Issue by iKramp** [Zorz42/Terralistic#64]
Post a comment with ores that should be added and maybe some generation details if needed (height at which it generates, frequency,...)

**Comment by Zorz42** [comment]
copper, tin. iron, lead, silver, tungsten, gold, platinum, obsidian, cobalt, palladium, mythril, orichalcum, adamantite, titanium, bismuth, silicon, calcium, barium, zync, mercury, nickel... ni treba lih vseh do zadnje sam fajn bi pa blo cim vec

**Comment by Zorz42** [comment]
ore list moved to caves and ores issue comment...
